version: "3.4"

x-common-variables:
  &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD:
  MYSQL_DATABASE: propsmanager
  MYSQL_ALLOW_EMPTY_PASSWORD: yes
  NODE_ENV: development
networks:
  app:
    driver: bridge
services:
  mysql-db:
    image: mysql:5.7.32
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
    ports:
      - 3306:3306
    networks:
      - app
    expose:
      - 3306
    restart: unless-stopped
    volumes:
      - ./db:/tmp/database
    # command: mysqld --init-file="/tmp/database/propsmanager.sql"
  server:
    build:
      dockerfile: Dockerfile.server
    container_name: node_server
    depends_on:
      - mysql-db
    networks:
      - app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
      PORT: 3001
      DB_HOST: mysql-db
    expose:
      - 3001
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - mysql-db
  client:
    build:
      dockerfile: Dockerfile.client
    container_name: node_client
    environment:
      PORT: 3000
    depends_on:
      - server
    networks:
      - app
    ports:
      - 3000:3000
    # volumes:
    #   - ./client:/usr/app
    #   - /usr/app/node_modules
    command: npm start


    # client:
    #   build: ./client
    #   container_name: node_client
    #   environment:
    #     <<: *common-variables
    #     NODE_PATH: src
    #   ports:
    #     - 3000:3000
    #   volumes:
    #     - ./client/src:/app/src
    #   links:
    #     - server
    #   command: npm start
