FROM node:14-alpine

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./client/package*.json .

RUN npm install

COPY ./client .

CMD [ "npm", "start" ]